# Generated by Django 4.0.2 on 2022-07-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdataagain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cou',
            name='ls',
            field=models.TextField(default='', null=True),
        ),
    ]
