# Generated by Django 4.0.2 on 2022-07-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdataagain', '0002_cou_ls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cou',
            name='ls',
        ),
        migrations.AddField(
            model_name='cou',
            name='inter_data',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='cou',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
