# Generated by Django 4.0.2 on 2022-07-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdataagain', '0003_remove_cou_ls_cou_inter_data_alter_cou_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='sta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('country_id', models.IntegerField()),
                ('inter_data', models.TextField(default='', max_length=4000)),
            ],
        ),
    ]
