# Generated by Django 4.0.2 on 2022-07-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdataagain', '0004_sta'),
    ]

    operations = [
        migrations.CreateModel(
            name='cit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_id', models.IntegerField()),
                ('country_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=200)),
                ('inter_data', models.TextField(default='', max_length=4000)),
            ],
        ),
    ]
